export const GET_DISTCODES = 'GET_DISTCODES'
export const SET_STATE = 'SET_STATE'
export const SET_KEEPSTATE = 'SET_KEEPSTATE'
export const SET_GPS = 'SET_GPS'
export const SET_SGPS = 'SET_SGPS'
export const SET_WXINFO = 'SET_WXINFO'
export const SET_GOEASY = 'SET_GOEASY'
